services:
  mongodb:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    
  health-hhg:
    depends_on:
      - mongodb
    image: hoffmanng/health-hhg:latest
    ports:
      - "3600:3600"
    restart: always
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/health-hhg"
      JWT_SECRET: "secretPrivateKey4534"

volumes:
  db_data: {}
